--- 
backend: 
  branch: main
  name: git-gateway
publish_mode: editorial_workflow
collections: 
  - 
    create: true
    extension: json
    fields: 
      - 
        label: Name
        name: name
        widget: string
      - 
        label: "Telephone Number"
        name: tel
        widget: string
      - 
        label: "Text Number"
        name: sms
        widget: string
        required: false
      - 
        label: "Website URL"
        name: url
        widget: string
        required: false
      - 
        label: "Chat Website URL"
        name: chat
        widget: string
        required: false
      - 
        label: Instructions
        name: instructions
        widget: text
        required: false
      - 
        label: "Language e.g. Press 3 for Spanish"
        name: language
        widget: string
        required: false
      - 
        collection: sources
        label: Source
        name: source
        search_fields: 
          - name
        value_field: name
        widget: relation
      - 
        collection: collections
        label: "Collection e.g. LGBTQIA+ or Domestic Abuse or Suicide Prevention"
        name: collection
        search_fields: 
          - name
          - id
        value_field: name
        widget: relation
    folder: _data/resources
    label: Resources
    name: resources
    slug: "resource-{{name}}"
  - 
    create: true
    extension: json
    fields: 
      - 
        label: Name
        name: name
        widget: string
      - 
        default: false
        label: "Show on Website?"
        name: active
        widget: boolean
      - 
        label: "Description (Optional)"
        name: description
        widget: text
        required: false
      - 
        label: "Website URL"
        name: url
        widget: text
    folder: _data/sources
    label: Sources
    name: sources
    slug: "source-{{name}}"
  - 
    create: true
    extension: json
    fields: 
      - 
        label: Name
        name: name
        widget: string
      - 
        label: Description
        name: description
        widget: text
        required: false
      - 
        label: "ID e.g. LGBTQIA could have \"queer\" or \"gay\" to make it easier to assign resources to this collection."
        name: id
        widget: string
    folder: _data/collections
    label: Collections
    name: collections
    slug: "collection-{{id}}"
media_folder: _site/_images
